// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPointsEvent = `-- name: CreatePointsEvent :one
INSERT INTO points_events (user_id, event_type, ref_id, points, meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_type, ref_id, points, meta, occurred_at
`

type CreatePointsEventParams struct {
	UserID    uuid.UUID             `json:"user_id"`
	EventType string                `json:"event_type"`
	RefID     sql.NullString        `json:"ref_id"`
	Points    int32                 `json:"points"`
	Meta      pqtype.NullRawMessage `json:"meta"`
}

func (q *Queries) CreatePointsEvent(ctx context.Context, arg CreatePointsEventParams) (PointsEvent, error) {
	row := q.db.QueryRowContext(ctx, createPointsEvent,
		arg.UserID,
		arg.EventType,
		arg.RefID,
		arg.Points,
		arg.Meta,
	)
	var i PointsEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.RefID,
		&i.Points,
		&i.Meta,
		&i.OccurredAt,
	)
	return i, err
}

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO redemptions (user_id, reward_id, points_spent)
VALUES ($1, $2, $3)
RETURNING id, user_id, reward_id, points_spent, status, created_at, updated_at
`

type CreateRedemptionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	RewardID    uuid.UUID `json:"reward_id"`
	PointsSpent int32     `json:"points_spent"`
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, createRedemption, arg.UserID, arg.RewardID, arg.PointsSpent)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RewardID,
		&i.PointsSpent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReward = `-- name: CreateReward :one
INSERT INTO rewards_catalog (name, description, cost, segment, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, cost, segment, active, created_by, created_at
`

type CreateRewardParams struct {
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	Cost        int32                 `json:"cost"`
	Segment     pqtype.NullRawMessage `json:"segment"`
	CreatedBy   uuid.NullUUID         `json:"created_by"`
}

func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (RewardsCatalog, error) {
	row := q.db.QueryRowContext(ctx, createReward,
		arg.Name,
		arg.Description,
		arg.Cost,
		arg.Segment,
		arg.CreatedBy,
	)
	var i RewardsCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Segment,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone)
VALUES ($1)
RETURNING id, phone, created_at
`

func (q *Queries) CreateUser(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.CreatedAt)
	return i, err
}

const getPointsEventsByUser = `-- name: GetPointsEventsByUser :many
SELECT id, user_id, event_type, ref_id, points, meta, occurred_at FROM points_events
WHERE user_id = $1
ORDER BY occurred_at DESC
`

func (q *Queries) GetPointsEventsByUser(ctx context.Context, userID uuid.UUID) ([]PointsEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPointsEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointsEvent{}
	for rows.Next() {
		var i PointsEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.RefID,
			&i.Points,
			&i.Meta,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedemption = `-- name: GetRedemption :one
SELECT id, user_id, reward_id, points_spent, status, created_at, updated_at FROM redemptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRedemption(ctx context.Context, id uuid.UUID) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, getRedemption, id)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RewardID,
		&i.PointsSpent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRedemptionsByUser = `-- name: GetRedemptionsByUser :many
SELECT id, user_id, reward_id, points_spent, status, created_at, updated_at FROM redemptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetRedemptionsByUser(ctx context.Context, userID uuid.UUID) ([]Redemption, error) {
	rows, err := q.db.QueryContext(ctx, getRedemptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Redemption{}
	for rows.Next() {
		var i Redemption
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RewardID,
			&i.PointsSpent,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReward = `-- name: GetReward :one
SELECT id, name, description, cost, segment, active, created_by, created_at FROM rewards_catalog
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReward(ctx context.Context, id uuid.UUID) (RewardsCatalog, error) {
	row := q.db.QueryRowContext(ctx, getReward, id)
	var i RewardsCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cost,
		&i.Segment,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getRewardsCatalog = `-- name: GetRewardsCatalog :many
SELECT id, name, description, cost, segment, active, created_by, created_at FROM rewards_catalog
WHERE active = true
ORDER BY cost ASC
`

func (q *Queries) GetRewardsCatalog(ctx context.Context) ([]RewardsCatalog, error) {
	rows, err := q.db.QueryContext(ctx, getRewardsCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RewardsCatalog{}
	for rows.Next() {
		var i RewardsCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cost,
			&i.Segment,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, phone, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.CreatedAt)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, created_at FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.CreatedAt)
	return i, err
}

const updateRedemptionStatus = `-- name: UpdateRedemptionStatus :one
UPDATE redemptions
SET status = $2
WHERE id = $1
RETURNING id, user_id, reward_id, points_spent, status, created_at, updated_at
`

type UpdateRedemptionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, updateRedemptionStatus, arg.ID, arg.Status)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RewardID,
		&i.PointsSpent,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
