// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePointsEvent(ctx context.Context, arg CreatePointsEventParams) (PointsEvent, error)
	CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error)
	CreateReward(ctx context.Context, arg CreateRewardParams) (RewardsCatalog, error)
	CreateUser(ctx context.Context, phone string) (User, error)
	GetPointsEventsByUser(ctx context.Context, userID uuid.UUID) ([]PointsEvent, error)
	GetRedemption(ctx context.Context, id uuid.UUID) (Redemption, error)
	GetRedemptionsByUser(ctx context.Context, userID uuid.UUID) ([]Redemption, error)
	GetReward(ctx context.Context, id uuid.UUID) (RewardsCatalog, error)
	GetRewardsCatalog(ctx context.Context) ([]RewardsCatalog, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	UpdateRedemptionStatus(ctx context.Context, arg UpdateRedemptionStatusParams) (Redemption, error)
}

var _ Querier = (*Queries)(nil)
